num1=int(input('enter your first number: '))
num2=int(input('enter your second number: '))
print("addition :",num1+num2)
print("subtraction :",num1-num2)
print("multiplication :",num1*num2)
print("division :,num1/num2)